version: '3'

services:
  payment:
    image: 'eclipse-temurin:17-jdk-alpine'
    working_dir: '/app'
    volumes:
      - '.:/app'
    command: ["./gradlew", "bootRun"]
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: 'mysql'
      MYSQL_DATABASE: 'payment'
      MYSQL_USER: 'payment'
      MYSQL_PASSWORD: 'password'

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_DATABASE: 'payment'
      MYSQL_USER: 'payment'
      MYSQL_PASSWORD: 'password'
    volumes:
      - 'payment-mysql:/var/lib/mysql'

volumes:
  payment-mysql:
