version: '3'

services:
  payment:
    image: 'eclipse-temurin:17-jdk-alpine'
    working_dir: '/app'
    networks:
      - payment
      - reconcip-microservices_infra
    volumes:
      - '.:/app'
    command: ["./gradlew", "bootRun"]
    ports:
      - '8002:${SERVER_PORT:-80}'
    environment:
      SERVER_PORT: '${SERVER_PORT:-80}'
      MYSQL_HOST: '${DB_HOST:-localhost}'
      MYSQL_DATABASE: '${DB_DATABASE:-database}'
      MYSQL_USER: '${DB_USER:-user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      JWT_TOKEN_SECRET: '${JWT_TOKEN_SECRET}'
      JWT_TOKEN_ISSUER: '${JWT_TOKEN_ISSUER}'
      JWT_TOKEN_AUDIENCE: '${JWT_TOKEN_AUDIENCE}'
      APP_NAME: '${APP_NAME:-payment}'
      ZIPKIN_URL: '${ZIPKIN_URL:-http://127.0.0.1:9411}'
      RABBITMQ_HOST: '${RABBITMQ_HOST:-localhost}'
      RABBITMQ_PORT: '${RABBITMQ_PORT}'
      RABBITMQ_USERNAME: '${RABBITMQ_USERNAME:-guest}'
      RABBITMQ_PASSWORD: '${RABBITMQ_PASSWORD:-guest}'

  mysql:
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_DATABASE: '${DB_DATABASE:-database}'
      MYSQL_USER: '${DB_USER:-user}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
    volumes:
      - 'payment-mysql:/var/lib/mysql'
    networks:
      - payment

networks:
  payment:
    driver: bridge
  reconcip-microservices_infra:
    external: true

volumes:
  payment-mysql:
