version: '3'
services:
    renting:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.2/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - renting
        depends_on:
            - redis
            - mysql
            - mailpit
            - zipkin
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - renting
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - renting
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - renting

    prometheus:
        image: 'prom/prometheus'
        ports:
            - '9090:9090'
        volumes:
            - './.secret:/etc/prometheus/secret'
            - './prometheus.yml:/etc/prometheus/prometheus.yml'
        networks:
            - renting

    storage:
        container_name: zipkin_mysql
        image: 'openzipkin/zipkin-mysql'
        networks:
            - renting

    zipkin:
        image: 'openzipkin/zipkin'
        ports:
            - '9411:9411'
        environment:
            STORAGE_TYPE: 'mysql'
            MYSQL_HOST: 'zipkin_mysql'
            MYSQL_USER: 'zipkin'
            MYSQL_PASS: 'zipkin'
        networks:
            - renting
        depends_on:
            - storage

    zipkin_dependencies:
        image: 'openzipkin/zipkin-dependencies'
        entrypoint: 'crond -f'
        environment:
            STORAGE_TYPE: 'mysql'
            MYSQL_HOST: 'zipkin_mysql'
            MYSQL_USER: 'zipkin'
            MYSQL_PASS: 'zipkin'
            ZIPKIN_LOG_LEVEL: 'DEBUG'
        depends_on:
            - storage

networks:
    renting:
        driver: bridge
volumes:
    sail-redis:
        driver: local
    sail-mysql:
        driver: local
