global:
  scrape_interval: 5s
  scrape_timeout: 3s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: renting
    metrics_path: /metrics
    authorization:
      credentials_file: secret
    static_configs:
      - targets: ['renting']

  - job_name: inventory
    metrics_path: /metrics
    authorization:
      credentials_file: secret
    static_configs:
      - targets: ['inventory']

  - job_name: pricing
    metrics_path: /metrics
    authorization:
      credentials_file: secret
    static_configs:
      - targets: ['pricing']

  - job_name: payment
    metrics_path: /actuator/prometheus
    authorization:
      credentials_file: secret
    static_configs:
      - targets: ['payment']
