version: '3'
services:
  gateway:
    image: 'golang'
    working_dir: '/app'
    command: ["go", "run", "cmd/main.go"]
    ports:
      - '8000:8000'
    environment:
      CONSUL_ADDR: '${CONSUL_ADDR:-127.0.0.1:8500}'
      JWT_SECRET: '${JWT_SECRET}'
      JWT_ISSUER: '${JWT_ISSUER}'
      JWT_AUDIENCE: '${JWT_AUDIENCE}'
      JWT_ALGORITHM: '${JWT_ALGORITHM}'
    volumes:
      - '.:/app'
    networks:
      - renting_renting

networks:
  renting_renting:
    external: true
