version: '3'

services:
  gateway:
    image: 'eclipse-temurin:17-jdk-alpine'
    working_dir: '/app'
    networks:
      - reconcip-microservices_infra
    volumes:
      - '.:/app'
    command: ["./gradlew", "bootRun"]
    ports:
      - '8000:${SERVER_PORT:-80}'
    environment:
      APP_NAME: '${APP_NAME:-gateway}'
      SERVER_PORT: '${SERVER_PORT:-80}'
      JWT_TOKEN_SECRET: '${JWT_TOKEN_SECRET}'
      JWT_TOKEN_ISSUER: '${JWT_TOKEN_ISSUER}'
      JWT_TOKEN_AUDIENCE: '${JWT_TOKEN_AUDIENCE}'
      JWT_TOKEN_ALGORITHM: '${JWT_TOKEN_ALGORITHM}'
      CONSUL_ADDR: '${CONSUL_ADDR:-127.0.0.1:8500}'
      ALLOWED_ORIGINS: '${ALLOWED_ORIGINS}'
      ALLOWED_METHODS: '${ALLOWED_METHODS}'
      ALLOWED_HEADERS: '${ALLOWED_HEADERS}'

networks:
  reconcip-microservices_infra:
    external: true
